version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: /Users/kawai/output.log
log-level: 1

tools:
  python-mypy: &python-mypy
    lint-command: "mypy --show-column-numbers"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

languages:
  python:
    - <<: *python-mypy
