require("snacks").setup({
	animate = { enabled = false },
	bigfile = { enabled = false },
	bufdelete = { enabled = false },
	dashboard = { enabled = false },
	debug = { enabled = false },
	dim = { enabled = false },
	explorer = { enabled = false },
	gh = { enabled = false },
	git = { enabled = false },
	gitbrowse = { enabled = false },
	image = { enabled = false },
	indent = { enabled = false },
	input = { enabled = false },
	keymap = { enabled = false },
	layout = { enabled = false },
	lazygit = { enabled = false },
	notifier = { enabled = false },
	notify = { enabled = false },
	picker = {
		enabled = false,
		win = {
			input = {
				keys = {
					["<Esc>"] = { "close", mode = { "n", "i" } },
					["<M-s>"] = { "edit_split", mode = { "i", "n" } },
					["<M-v>"] = { "edit_vsplit", mode = { "i", "n" } },
				},
			},
			list = {
				keys = {},
			},
		},
	},
	profiler = { enabled = false },
	quickfile = { enabled = false },
	rename = { enabled = false },
	scope = { enabled = false },
	scratch = { enabled = false },
	scroll = { enabled = false },
	statuscolumn = { enabled = false },
	terminal = { enabled = false },
	toggle = { enabled = false },
	util = { enabled = false },
	win = { enebled = false },
	words = { enabled = false },
	zen = { enabled = false },
})
