require("snacks").setup({
	bigfile = { enabled = true },
	dashboard = { enabled = false },
	explorer = { enabled = true },
	indent = { enabled = true },
	input = { enabled = true },
	picker = {
		enabled = true,
		win = {
			input = {
				keys = {
					["<Esc>"] = { "close", mode = { "n", "i" } },
				},
			},
			list = {
				keys = {
					["/"] = "toggle_focus",
					["<2-LeftMouse>"] = "confirm",
					["<CR>"] = "confirm",
					["<Down>"] = "list_down",
					["<Esc>"] = "cancel",
					["<S-CR>"] = { { "pick_win", "jump" } },
					["<S-Tab>"] = { "select_and_prev", mode = { "n", "x" } },
					["<Tab>"] = { "select_and_next", mode = { "n", "x" } },
					["<Up>"] = "list_up",
					["<a-d>"] = "inspect",
					["<a-f>"] = "toggle_follow",
					["<a-h>"] = "toggle_hidden",
					["<a-i>"] = "toggle_ignored",
					["<a-m>"] = "toggle_maximize",
					["<a-p>"] = "toggle_preview",
					["<a-w>"] = "cycle_win",
					["<c-a>"] = "select_all",
					["<c-b>"] = "preview_scroll_up",
					["<c-d>"] = "list_scroll_down",
					["<c-f>"] = "preview_scroll_down",
					-- ["<c-j>"] = "list_down",
					-- ["<c-k>"] = "list_up",
					["<c-n>"] = "list_down",
					["<c-p>"] = "list_up",
					["<c-q>"] = "qflist",
					["<c-g>"] = "print_path",
					["<c-s>"] = "edit_split",
					["<c-t>"] = "tab",
					["<c-u>"] = "list_scroll_up",
					["<c-v>"] = "edit_vsplit",
					["<c-w>H"] = "layout_left",
					["<c-w>J"] = "layout_bottom",
					["<c-w>K"] = "layout_top",
					["<c-w>L"] = "layout_right",
					["?"] = "toggle_help_list",
					["G"] = "list_bottom",
					["gg"] = "list_top",
					["i"] = "focus_input",
					["j"] = "list_down",
					["k"] = "list_up",
					["q"] = "cancel",
					["zb"] = "list_scroll_bottom",
					["zt"] = "list_scroll_top",
					["zz"] = "list_scroll_center",
				},
			},
		},
	},
	notifier = { enabled = true },
	quickfile = { enabled = true },
	scope = { enabled = true },
	scroll = { enabled = true },
	statuscolumn = { enabled = true },
	words = { enabled = true },
})
