require("snacks").setup({
	bigfile = { enabled = true },
	dashboard = { enabled = false },
	explorer = { enabled = true },
	indent = { enabled = true },
	input = { enabled = true },
	picker = {
		enabled = true,
		win = {
			input = {
				keys = {
					["<Esc>"] = { "close", mode = { "n", "i" } },
					["/"] = "toggle_focus",
					["<C-Down>"] = { "history_forward", mode = { "i", "n" } },
					["<C-Up>"] = { "history_back", mode = { "i", "n" } },
					["<C-c>"] = { "cancel", mode = "i" },
					["<C-w>"] = { "<c-s-w>", mode = { "i" }, expr = true, desc = "delete word" },
					["<CR>"] = { "confirm", mode = { "n", "i" } },
					["<Down>"] = { "list_down", mode = { "i", "n" } },
					["<S-CR>"] = { { "pick_win", "jump" }, mode = { "n", "i" } },
					["<S-Tab>"] = { "select_and_prev", mode = { "i", "n" } },
					["<Tab>"] = { "select_and_next", mode = { "i", "n" } },
					["<Up>"] = { "list_up", mode = { "i", "n" } },
					["<a-d>"] = { "inspect", mode = { "n", "i" } },
					["<a-f>"] = { "toggle_follow", mode = { "i", "n" } },
					["<a-h>"] = { "toggle_hidden", mode = { "i", "n" } },
					["<a-i>"] = { "toggle_ignored", mode = { "i", "n" } },
					["<a-r>"] = { "toggle_regex", mode = { "i", "n" } },
					["<a-m>"] = { "toggle_maximize", mode = { "i", "n" } },
					["<a-p>"] = { "toggle_preview", mode = { "i", "n" } },
					["<a-w>"] = { "cycle_win", mode = { "i", "n" } },
					["<c-a>"] = { "select_all", mode = { "n", "i" } },
					["<c-b>"] = { "preview_scroll_up", mode = { "i", "n" } },
					["<c-d>"] = { "list_scroll_down", mode = { "i", "n" } },
					["<c-f>"] = { "preview_scroll_down", mode = { "i", "n" } },
					["<c-g>"] = { "toggle_live", mode = { "i", "n" } },
					["<c-j>"] = { "list_down", mode = { "i", "n" } },
					["<c-k>"] = { "list_up", mode = { "i", "n" } },
					["<c-n>"] = { "list_down", mode = { "i", "n" } },
					["<c-p>"] = { "list_up", mode = { "i", "n" } },
					["<c-q>"] = { "qflist", mode = { "i", "n" } },
					["<c-s>"] = { "edit_split", mode = { "i", "n" } },
					["<c-t>"] = { "tab", mode = { "n", "i" } },
					["<c-u>"] = { "list_scroll_up", mode = { "i", "n" } },
					["<c-v>"] = { "edit_vsplit", mode = { "i", "n" } },
					["<c-r>#"] = { "insert_alt", mode = "i" },
					["<c-r>%"] = { "insert_filename", mode = "i" },
					["<c-r><c-a>"] = { "insert_cWORD", mode = "i" },
					["<c-r><c-f>"] = { "insert_file", mode = "i" },
					["<c-r><c-l>"] = { "insert_line", mode = "i" },
					["<c-r><c-p>"] = { "insert_file_full", mode = "i" },
					["<c-r><c-w>"] = { "insert_cword", mode = "i" },
					["<c-w>H"] = "layout_left",
					["<c-w>J"] = "layout_bottom",
					["<c-w>K"] = "layout_top",
					["<c-w>L"] = "layout_right",
					["?"] = "toggle_help_input",
					["G"] = "list_bottom",
					["gg"] = "list_top",
					["j"] = "list_down",
					["k"] = "list_up",
					["q"] = "cancel",
				},
			},
			list = {
				keys = {},
			},
		},
	},
	notifier = { enabled = true },
	quickfile = { enabled = true },
	scope = { enabled = true },
	scroll = { enabled = true },
	statuscolumn = { enabled = true },
	words = { enabled = true },
})
