[colors]
foreground = "#b4b1ba"
background = "#121213"
cursor_bg = "#666370"
cursor_border = "#666370"
cursor_fg = "#121213"
selection_bg = "#363639"
selection_fg = "#b4b1ba"
scrollbar_thumb = "#504d54"
split = "#504d54"

ansi = [
  "#202023", # black
  "#e27598", # red
  "#80a891", # green
  "#d4a48c", # yellow
  "#8292c7", # blue
  "#d68abc", # magenta
  "#76a5aa", # cyan
  "#b4b1ba", # white
]

brights = [
  "#3a3a3e", # bright black
  "#e889a9", # bright red
  "#9bc3ab", # bright green
  "#e6b9a3", # bright yellow
  "#9dadd5", # bright blue
  "#e4a6d0", # bright magenta
  "#8cbcc0", # bright cyan
  "#c9c7cd", # bright white
]
