[completion]
activate_on_typing = true
copilot = false

[display]
theme = "light"
code_editor_font_size = 14
cell_output = "above"
default_width = "medium"
dataframes = "rich"
default_table_page_size = 10
reference_highlighting = false

[formatting]
line_length = 79

[keymap]
preset = "default"

[keymap.overrides]

[runtime]
auto_instantiate = true
auto_reload = "off"
reactive_tests = true
on_cell_change = "autorun"
watcher_on_save = "lazy"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
default_sql_output = "auto"

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = false

[package_management]
manager = "uv"

[server]
browser = "default"
follow_symlink = false

[language_servers.pylsp]
enabled = true
enable_mypy = true
enable_ruff = true
enable_flake8 = false
enable_pydocstyle = false
enable_pylint = false
enable_pyflakes = false

[snippets]
custom_paths = []
include_default_snippets = true
