[keymap]
preset = "default"

[keymap.overrides]

[experimental]

[server]
browser = "default"
follow_symlink = false

[package_management]
manager = "uv"

[language_servers.pylsp]
enabled = false
enable_pydocstyle = false
enable_pyflakes = false
enable_ruff = true
enable_mypy = true
enable_flake8 = false
enable_pylint = false

[display]
cell_output = "below"
code_editor_font_size = 14
theme = "light"
dataframes = "rich"
reference_highlighting = true
default_table_page_size = 10
default_width = "full"

[snippets]
custom_paths = []
include_default_snippets = true

[diagnostics]
enabled = false

[runtime]
reactive_tests = true
std_stream_max_bytes = 1000000
auto_reload = "off"
output_max_bytes = 8000000
watcher_on_save = "lazy"
auto_instantiate = true
on_cell_change = "autorun"
default_sql_output = "auto"

[save]
autosave_delay = 1000
format_on_save = false
autosave = "after_delay"

[formatting]
line_length = 79

[completion]
activate_on_typing = true
copilot = false

[ai]
rules = ""
mode = "manual"

[ai.google]

[ai.open_ai]

[ai.bedrock]

[ai.anthropic]

[snipets]
custom_paths = ["/Users/kawai/.config/marimo/custom.css"]
# include_default_snipetts = true
