[server]
follow_symlink = false
browser = "default"

[snippets]
include_default_snippets = true
custom_paths = []

[ai]
mode = "manual"
rules = ""

[ai.open_ai]

[ai.bedrock]

[ai.anthropic]

[ai.google]

[experimental]

[formatting]
line_length = 79

[language_servers.pylsp]
enable_mypy = true
enable_pylint = false
enable_flake8 = false
enable_ruff = true
enable_pyflakes = false
enable_pydocstyle = false
enabled = false

[runtime]
watcher_on_save = "lazy"
auto_reload = "off"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
auto_instantiate = true
on_cell_change = "autorun"
default_sql_output = "auto"
reactive_tests = true

[package_management]
manager = "uv"

[diagnostics]
enabled = false

[keymap]
preset = "default"

[keymap.overrides]

[completion]
copilot = false
activate_on_typing = true

[display]
default_width = "full"
reference_highlighting = true
dataframes = "rich"
default_table_page_size = 10
cell_output = "above"
theme = "light"
code_editor_font_size = 14

[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000
