if [ "$(uname -s)" = 'Linux' ]; then
	export LANG=en_US.UTF-8
	if [ -e /etc/lsb-release ]; then
		export HTTP_PROXY="172.20.131.3:8065"
		export http_proxy="172.20.131.3:8065"
		export HTTPS_PROXY="172.20.131.3:8065"
		export https_proxy="172.20.131.3:8065"
	fi
fi

export ZDOTDIR=$HOME/.config/zsh

if [ -d $HOME/bin ]; then
	export PATH=$HOME/bin:$PATH
fi
