#!/bin/sh

use_jupyter () {
	export IPYTHONDIR="$VIRTUAL_ENV/.ipython"
	export JUPYTER_CONFIG_DIR="$VIRTUAL_ENV/.jupyter"
}

use_rdkit () {
	export RDBASE="$PWD/RDKit"
	export LD_LIBRARY_PATH="$VIRTUAL_ENV/lib":"$HOME/.linuxbrew/lib":$LD_LIBRARY_PATH
}

use_gpu () {
	export CUDA_ROOT="/usr/local/cuda"
	export PATH="/usr/local/cuda/bin":$PATH
	export CUDA_VISIBLE_DEVICES=0
	export LD_LIBRARY_PATH="/usr/local/cuda/lib64":$LD_LIBRARY_PATH
}
