#!/bin/sh

use_jupyter() {
	export MPLCONFIGDIR=${XDG_CONFIG_HOME}/matplotlib

	export IPYTHONDIR=${XDG_CONFIG_HOME}/ipython

	export JUPYTER_CONFIG_DIR=${XDG_CONFIG_HOME}/jupyter
	export JUPYTER_DATA_DIR=${XDG_DATA_HOME}/jupyter

	export JUPYTERLAB_DIR=${XDG_DATA_HOME}/jupyter/lab
	export JUPYTERLAB_SETTINGS_DIR=${XDG_CONFIG_HOME}/jupyter/lab
	export JUPYTERLAB_WORKSPACES_DIR=${XDG_DATA_HOME}/jupyter/lab
}
