[lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "W",   # pycodestyle
  "I",   # isort
  "N",   # pep8-naming
  "B",   # flake8-bugbear
  "PL",  # pylint
  "PD",  # pandas-vet
  "NPY", # numpy
  "RUF", # ruff
  "UP",  # pyupgrade
  "D",   # pydocstyle
]
ignore = [
  "I001",    # isort
  "D100",    # Missing docstring in public module
  "D104",    # Missing docstring in public package
  "D105",    # Missing docstring in magic method
  "E501",    # Line too long
  "PLR0913", # Too many arguments
  "PLR2004", # magic-value-comparison
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"**/tests/test_a.py" = ["D"]
"**/{tests,docs,tools}/*" = ["D"]

[lint.pydocstyle]
convention = "google"
